include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_redundant_argument_values: true
    prefer_relative_imports: true
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false
    require_trailing_commas: false
